--EJERCICIO 1
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='EMPLE';

CREATE TABLE EMPLEADOS30 AS SELECT * FROM EMPLE WHERE DEPT_NO=30;
DESC EMPLEADOS30

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('EMPLE', 'EMPLEADOS30');

--EJERCICIO 2
SELECT *
FROM EMPLE;

INSERT INTO EMPLE('2000', 'SAAVEDRO',SELECT OFICIO FROM EMPLE WHERE APELLIDO='SALA' ,SYSDATE,
(SELECT SALARIO FROM EMPLE WHERE APELLIDO='SALA')*120/100,
SELECT COMISION_PCT FROM EMPLE WHERE APELLIDO='SALA', SELECT DEPT_NO FROM EMPLE WHERE APELLIDO='SALA');
