--EJERCICIO 1

SELECT AVG(SALARIO) AS "MEDIA SALARIO", MAX(SALARIO) AS "SALARIO MAXIMO",
    MIN(SALARIO) AS "SALARIO MINIMO", SUM(SALARIO) AS "SUMA SALARIO"
FROM EMPLE
WHERE UPPER(OFICIO)='COMERCIAL'

--EJERCICIO 2

SELECT MAX(FECHA_ALTA) AS "MENOR ANTIGUEDAD",
       MIN(FECHA_ALTA) AS "MAYOR ANTIGUEDAD"
FROM EMPLE;

SELECT APELLIDO, FECHA_ALTA
FROM EMPLE
WHERE FECHA_ALTA IN (SELECT MIN(FECHA_ALTA)
                    FROM EMPLE);