--EJERCICIO 1
SELECT APELLIDO AS "EMPLEADO", NVL(TO_CHAR(ID_JEFE), 'NO TIENE JEFE') AS "JEFE"
FROM EMPLE
ORDER BY ID_JEFE DESC;

--EJERCICIO 2
--TRUNC(SALARIO/1000,0) EL 0 INDICA EL NUMERO DE DEFINALES QUE QUIERES QUE APAREZCAN EN EL RESULTADO
--TRUNC ELIMINA TODOS LOS DECIMALES 
--ROUND HACE UN REDONDEO SI ES MAYOR DE 5 EL DECIMAL REDONDEA PARA ARRIBA
SELECT EMP_NO|| ' ' || APELLIDO  as "EMPLEADO", SALARIO, TRUNC(SALARIO/1000,0)|| '%' AS "PORCENTAJE DE MOVILIZACION"
FROM EMPLE

--EJERCICIO 3
-- LAS CADENAS EMPIEZAN EN 1 ¡EL 0 NO EXISTE!
SELECT EMP_NO AS "CODIGO EMPLEADO", APELLIDO, OFICIO, INITCAP(SUBSTR(APELLIDO,1,3)) || LENGTH(APELLIDO) || LOWER(OFICIO) AS "NOMBRE DE USUARIO",
        EXTRACT(MONTH FROM FECHA_ALTA) || SUBSTR(EXTRACT(YEAR FROM FECHA_ALTA),2,2) || REVERSE(SUBSTR(REVERSE(APELLIDO),1,2)) AS "CLAVE"
FROM EMPLE
ORDER BY APELLIDO;

SELECT EXTRACT(MONTH FROM FECHA_ALTA) || SUBSTR(EXTRACT(YEAR FROM FECHA_ALTA),2,2) AS "MI SOLUCION",
        TO_CHAR(FECHA_ALTA, 'MMYY') AS "CLASE"
FROM EMPLE;

SELECT REVERSE(SUBSTR(REVERSE(APELLIDO),1,2)) AS "MI SOLUCION", SUBSTR(APELLIDO,-2) AS "CLASE" 
FROM EMPLE

--EJERCICIO 4
SELECT EMP_NO AS "CODIGO EMPLEADO", APELLIDO, TO_CHAR(SALARIO, '999,999.999') AS "SALARIO ACTUAL", SUBSTR(SALARIO,1,1) || '%' AS "PORCENTAJE DE REAJUSTE",
        TO_CHAR(SALARIO*SUBSTR(SALARIO,1,1)/100+SALARIO,'9,999.999') AS "SALARIO NUEVO"
FROM EMPLE

--EJERCICIO 5
SELECT EMP_NO AS "ID_EMP", SALARIO AS "SALARIO ACTUAL",
    NVL(TO_CHAR(COMISION_PCT), 'SIN COMISION') AS "PORCENTAJE COMISION",
    NVL((COMISION_PCT*SALARIO)/100,0) ||'%' AS "COMISION",
    NVL(SALARIO+(COMISION_PCT*SALARIO)/100,SALARIO) AS "SALARIO TOTAL CALCULADO"
FROM EMPLE

--EJERCICIO 5.1 EL NOMBRE DEL DEPARTAMENTO DEL QUE TRABAJA
SELECT EMP_NO AS "ID_EMP", SALARIO AS "SALARIO ACTUAL",
    NVL(TO_CHAR(COMISION_PCT), 'SIN COMISION') AS "PORCENTAJE COMISION",
    NVL((COMISION_PCT*SALARIO)/100,0) ||'%' AS "COMISION",
    NVL(SALARIO+(COMISION_PCT*SALARIO)/100,SALARIO) AS "SALARIO TOTAL CALCULADO",
    DNOMBRE AS "DEPARTAMENTO"
FROM EMPLE, DEPART
WHERE EMPLE.DEPT_NO = DEPART.DEPT_NO;

--EJERCICIO 6
