--EJERCICIO1
INSERT INTO DEPART (DEPT_NO, DNOMBRE, LOC) VALUES (11,'CALIDAD','SANTANDER');

INSERT INTO EMPLE(EMP_NO,APELLIDO,OFICIO,DEPT_NO,FECHA_ALTA,SALARIO) VALUES(7230,'AGUIRRE','EMPLEADO',SYSDATE,11,2000);

SELECT EMP_NO,APELLIDO,OFICIO,DEPT_NO,SALARIO
FROM EMPLE;

SELECT DEPT_NO, DNOMBRE, LOC
FROM DEPART;

COMMIT;
--EJERCICIO 2
SELECT SALARIO
FROM EMPLE;

UPDATE EMPLE
SET SALARIO= SALARIO*0.90;

COMMIT;
--EJERCICIO 3
SELECT EMP_NO, DEPT_NO FROM EMPLE WHERE DEPT_NO IN(40,10);

UPDATE EMPLE SET DEPT_NO=40 WHERE DEPT_NO=10;
--SI EL ENUNCIADO FUERA DEPARTAMENTO PRODUCCION SIN SABER EL CODIGO
/*
SELECT EMP_NO, DEPT_NO FROM EMPLE WHERE DEPT_NO IN 
    (SELECT DEPT_NO 
    FROM DEPART
    WHERE UPPER(DNOMBRE) IN ('PRODUCCION','CONTABILIDAD'))
*/
/*
UPDATE EMPLE
SET DEPT_NO = (SELECT DEPT_NO FROM DEPART WHERE (UPPER(NOMBRE)='PRODUCCION') )
WHERE DEPT_NO=(SELECT DEPT_NO FROM DEPART WHERE (UPPER(NOMBRE)='CONTABILIDAD') )
*/

COMMIT;
--EJERCICIO 4
SELECT * FROM EMPLE;
UPDATE EMPLE
SET ID_JEFE= (SELECT ID_JEFE FROM EMPLE WHERE APELLIDO='TOVAR')
WHERE ID_JEFE=7566;

COMMIT;
--EJERCICIO 5
UPDATE EMPLE
SET SALARIO= NVL((SELECT SALARIO FROM EMPLE WHERE APELLIDO='MUNOZ'),0)
                    WHERE OFICIO='EMPLEADO';

SELECT OFICIO, SALARIO FROM EMPLE;

COMMIT;
--EJERCICIO 6
UPDATE EMPLE
SET SALARIO= SALARIO+300
WHERE DEPT_NO=(SELECT DEPT_NO FROM DEPART WHERE DNOMBRE='SANTANDER');
SELECT SALARIO FROM EMPLE;
COMMIT;
--EJERCICIO 7
SELECT * FROM EMPLE;

DELETE FROM EMPLE
WHERE DEPT_NO=30;
COMMIT;