--EJERCICIO 1
SELECT APELLIDO
FROM EMPLE 
WHERE OFICIO IN(SELECT DISTINCT OFICIO FROM EMPLE WHERE UPPER(APELLIDO)='GIL') AND UPPER(APELLIDO)!= 'GIL';

--EJERCICIO 2
SELECT *
FROM EMPLE
WHERE DEPT_NO IN (SELECT DEPT_NO FROM DEPART WHERE UPPER(LOC) IN('MADRID','BARCELONA'));

--EJERCICIO 3
SELECT APELLIDO
FROM EMPLE 
WHERE OFICIO IN (SELECT OFICIO FROM EMPLE WHERE UPPER(APELLIDO)='GIL') 
AND SALARIO IN (SELECT SALARIO FROM EMPLE WHERE UPPER(APELLIDO)='GIL')
AND UPPER(APELLIDO)!= 'GIL';



--EJERCICIO 4
SELECT APELLIDO, OFICIO, SALARIO, FECHA_ALTA
FROM EMPLE
WHERE OFICIO IN (SELECT OFICIO FROM EMPLE WHERE UPPER(APELLIDO)='JIMENEZ')
OR SALARIO>= ANY(SELECT SALARIO FROM EMPLE WHERE UPPER(APELLIDO)='FERNANDEZ');

INSERT INTO EMPLE VALUES(1111, 'FERNANDEZ','VENTAS',7839,SYSDATE,1950,8,10);

ROLLBACK;
--EJERCICIO 5
SELECT DEPT_NO, COUNT(EMP_NO) AS "NUMERO MAXIMO"
FROM EMPLE
GROUP BY DEPT_NO
HAVING COUNT(EMP_NO)=(SELECT MAX(COUNT(EMP_NO))
FROM EMPLE
GROUP BY DEPT_NO);

--EJERCICIO 6
SELECT OFICIO, AVG(SALARIO)
FROM EMPLE
GROUP BY OFICIO
HAVING AVG(SALARIO)IN(SELECT MIN(AVG(SALARIO)) FROM EMPLE GROUP BY OFICIO);

--EJERCICIO 7 --> DEVUELVE MAS DE UN VALOR POR LO QUE HAY QUE USAR EL IN
SELECT EMP_NO, APELLIDO
FROM EMPLE
WHERE SALARIO IN ( SELECT MIN(SALARIO)
				FROM EMPLE
				GROUP BY DEPT_NO);
                
--EJERCICIO 8 --> QUE NO HAY NINGUN PEREZ EN LA BASE DE DATOS Y QUE PUEDE ESTAR GUARDADO EN MINUSCULAS PEREZ
SELECT APELLIDO, OFICIO
FROM EMPLE
WHERE OFICIO = ( SELECT OFICIO
			FROM EMPLE
			WHERE APELLIDO = 'PEREZ');

-->NO SALDRIA PORQUE CON ESE CODIGO NO TRABAJARIA VALORES NULOS

--EJERCICIO 9
SELECT E1.APELLIDO
FROM EMPLE E1
WHERE E1.EMP_NO NOT IN(SELECT E.ID_JEFE FROM EMPLE E WHERE E1.EMP_NO=E.ID_JEFE);

--EJERCICIO 10
SELECT APELLIDO
FROM EMPLE
WHERE EMP_NO IN(SELECT ID_JEFE FROM EMPLE);

--EJERCICIO 11

SELECT EMP_NO, APELLIDO
FROM EMPLE
WHERE DEPT_NO IN(SELECT DEPT_NO FROM EMPLE WHERE UPPER(APELLIDO) LIKE '%U%');

--EJERCICIO 12

SELECT EMP_NO, APELLIDO
FROM EMPLE
WHERE DEPT_NO IN(SELECT DEPT_NO FROM EMPLE WHERE UPPER(APELLIDO) LIKE '%U%') 
AND SALARIO> (SELECT AVG(SALARIO) FROM EMPLE);

--EJERCICIO 13

SELECT APELLIDO, DEPT_NO, SALARIO
FROM EMPLE
WHERE DEPT_NO IN (SELECT DEPT_NO FROM EMPLE)
AND SALARIO IN (SELECT SALARIO FROM EMPLE) 
AND COMISION_PCT IS NOT NULL;

--EJERCICIO 14