--EJERCICIO 1

SELECT AVG(SALARIO) AS "MEDIA SALARIO", MAX(SALARIO) AS "SALARIO MAXIMO",
    MIN(SALARIO) AS "SALARIO MINIMO", SUM(SALARIO) AS "SUMA SALARIO"
FROM EMPLE
WHERE UPPER(OFICIO)='COMERCIAL'

--EJERCICIO 2

SELECT MAX(FECHA_ALTA) AS "MENOR ANTIGUEDAD",
       MIN(FECHA_ALTA) AS "MAYOR ANTIGUEDAD"
FROM EMPLE;

SELECT APELLIDO, FECHA_ALTA
FROM EMPLE
WHERE FECHA_ALTA IN (SELECT MIN(FECHA_ALTA)
                    FROM EMPLE);
                    
--EJERCICIO 3

SELECT MIN(APELLIDO) AS "PRIMERO" , MAX(APELLIDO) AS "ULTIMO"
FROM EMPLE;

--EJERCICIO 4

SELECT COUNT (EMP_NO) AS "EMPLEADOS DEPT 40"
FROM EMPLE
WHERE DEPT_NO = 40;

--EJERCICIO 5

SELECT COUNT (COMISION_PCT) AS "EMPLEADOS DEPT30 SINCOMISION"
FROM EMPLE
WHERE DEPT_NO = 30;

--EJERCICIO 6

SELECT COUNT(DISTINCT(DEPT_NO)) AS "DEPARTAMENTOS TOTALES"
FROM EMPLE;

--EJERCICIO 7

SELECT COUNT(EMP_NO) AS "Nº DE EMPLEADOS", DEPT_NO AS "NUMERO DEPARTAMENTO"
FROM EMPLE
GROUP BY DEPT_NO;

--EJERCICIO 8

SELECT COUNT(EMP_NO) AS "Nº DE EMPLEADOS", DEPT_NO AS "NUMERO DEPARTAMENTO"
FROM EMPLE
GROUP BY DEPT_NO
HAVING COUNT(EMP_NO) > 4;
