--EJERCICIO 1
SELECT APELLIDO, OFICIO, EMP_NO, DNOMBRE, LOC
FROM EMPLE, DEPART
WHERE EMPLE.DEPT_NO=DEPART.DEPT_NO;

--EJERCICIO 2
SELECT EMP_NO, APELLIDO, OFICIO, ID_JEFE, FECHA_ALTA, SALARIO, COMISION_PCT, EMPLE.DEPT_NO, DEPART.LOC
FROM EMPLE, DEPART
WHERE EMPLE.DEPT_NO=DEPART.DEPT_NO AND UPPER(LOC) IN ('MADRID', 'BARCELONA');

--EJERCICIO 3
SELECT E.EMP_NO AS "NUMERO EMPLEADO", E.APELLIDO AS "APELLIDO EMPLEADO",  J.APELLIDO AS "APELLIDO JEFE"
FROM EMPLE E,EMPLE J
WHERE J.EMP_NO=E.ID_JEFE;

--EJERCICIO 4
SELECT APELLIDO, OFICIO, LOC
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO AND UPPER(OFICIO) = 'ANALISTA';

--EJERCICIO 5
SELECT E.EMP_NO AS "NUMERO EMPLEADO", E.APELLIDO AS "APELLIDO EMPLEADO",  NVL(J.APELLIDO,'NO TIENE JEFE') AS "APELLIDO JEFE"
FROM EMPLE E,EMPLE J
WHERE E.ID_JEFE=J.EMP_NO(+);

--EJERCICIO 6
SELECT D.DEPT_NO,D.DNOMBRE, E.APELLIDO
FROM DEPART D, EMPLE E
WHERE D.DEPT_NO=E.DEPT_NO(+);