--EJERCICIO 1
SELECT DISTINCT E.OFICIO, D.LOC
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO= D.DEPT_NO AND D.DEPT_NO =10;

--EJERCICIO 2
SELECT D.DEPT_NO, D.DNOMBRE, COUNT(E.EMP_NO) "NUMERO DE EMPLEADOS"
FROM EMPLE E, DEPART D
WHERE D.DEPT_NO=E.DEPT_NO(+)
GROUP BY D.DEPT_NO, D.DNOMBRE
ORDER BY D.DEPT_NO;

--EJERCICIO 3
SELECT E.DEPT_NO, D.DNOMBRE, COUNT(E.EMP_NO) "NUMERO DE EMPLEADOS MAXIMO"
FROM EMPLE E, DEPART D
WHERE D.DEPT_NO=E.DEPT_NO
GROUP BY E.DEPT_NO,D.DNOMBRE
HAVING COUNT(E.EMP_NO)=(SELECT MAX(COUNT(E.EMP_NO)) FROM EMPLE GROUP BY DEPT_NO);

--EJERCICIO 4
SELECT E.APELLIDO, D.DNOMBRE, E.SALARIO
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO= D.DEPT_NO AND E.SALARIO IN (SELECT SALARIO 
                                        FROM EMPLE, DEPART
                                        WHERE EMPLE.DEPT_NO=DEPART.DEPT_NO AND UPPER(LOC)='BARCELONA')
AND NVL(E.COMISION_PCT,0) IN(SELECT NVL(COMISION_PCT,0) 
                    FROM EMPLE, DEPART
                    WHERE EMPLE.DEPT_NO=DEPART.DEPT_NO AND UPPER(LOC)='BARCELONA')
AND UPPER(LOC)!='BARCELONA';
