--EJERCICIO 1

SELECT EMP_NO,APELLIDO, OFICIO, DEPT_NO
FROM EMPLE
WHERE UPPER(OFICIO)='ANALISTA' AND DEPT_NO = 20
ORDER BY APELLIDO DESC, EMP_NO DESC;

--EJERCICIO 2

SELECT APELLIDO, OFICIO, FECHA_ALTA
FROM EMPLE
WHERE FECHA_ALTA BETWEEN TO_DATE('01/05/1981','DD/MM/YYYY') AND TO_DATE('30/09/1981','DD/MM/YYYY')
ORDER BY FECHA_ALTA;

--EJERCICIO 3

SELECT (APELLIDO || ' , '|| OFICIO) AS "EMPLE Y OFI"
FROM EMPLE
WHERE OFICIO LIKE '%R%'
ORDER BY APELLIDO;

--EJERCICIO 4

SELECT DISTINCT OFICIO
FROM EMPLE;

--EJERCICIO 5

SELECT EMP_NO, APELLIDO, SALARIO AS "SALARIO MENSUAL" , SALARIO*12 AS "SALARIO ANUAL"
FROM EMPLE
WHERE SALARIO*12 NOT BETWEEN 9000 AND 20000;

--EJERCICIO 6

SELECT APELLIDO, COMISION_PCT
FROM EMPLE
WHERE COMISION_PCT IS NOT NULL;

-- EJERCICIO 7

SELECT APELLIDO || ' NO TIENE COMISION' AS "COMISION"
FROM EMPLE
WHERE COMISION_PCT IS NULL;

--EJERCICIO 8

SELECT APELLIDO, SALARIO, NVL(TO_CHAR(COMISION_PCT),'NO TIENE COMISION')
FROM EMPLE;

--VER LAS TABLAS QUE TIENES INSERTADAS

SELECT USER_CONSTRAINTS.TABLE_NAME, USER_CONSTRAINTS.CONSTRAINT_NAME, USER_CONSTRAINTS.CONSTRAINT_TYPE, SEARCH_CONDITION, USER_CONS_COLUMNS.COLUMN_NAME
FROM USER_CONSTRAINTS, USER_CONS_COLUMNS
WHERE UPPER(USER_CONSTRAINTS.TABLE_NAME) IN ('EMPLE', 'DEPART') 
AND USER_CONSTRAINTS.CONSTRAINT_NAME=USER_CONS_COLUMNS.CONSTRAINT_NAME;