
--EJERCICIO 2
SELECT TABLE_NAME
FROM USER_TABLES;

--EJERCICIO 3
ALTER TABLE TIENDAS ADD(
CONSTRAINT TIE_NOM_CK CHECK (NOMBRE=INITCAP(NOMBRE))
);

--EJERCICIO4
SELECT OWNER,CONSTRAINT_NAME,CONSTRAINT_TYPE,TABLE_NAME,SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE UPPER(TABLE_NAME) IN ('ARTICULOS','VENTAS','TIENDAS','PEDIDOS','FABRICANTES');

--EJERCICIO 5
ALTER TABLE PEDIDOS MODIFY (
UNIDADES_PEDIDAS NUMBER(6)

);

ALTER TABLE VENTAS MODIFY (
UNIDADES_VENDIDAS NUMBER(6)

);
--EJERCICIO6
ALTER TABLE TIENDAS MODIFY(
CONSTRAINT TIE_PROVI_CK CHECK(UPPER(PROVINCIA)!='TOLEDO')
);


--EJERCICIO 7
ALTER TABLE VENTAS ADD(
PVP NUMBER(6) DEFAULT 0

);

ALTER TABLE PEDIDOS ADD(
PVP NUMBER(6) DEFAULT 0

);
--EJERCICIO 8
ALTER TABLE PEDIDOS DROP(
PVP
);

ALTER TABLE VENTAS DROP(
PVP
);
