-- EJERCICIO 1
SELECT COUNT(EMP_NO) AS "Nº DE EMPLEADOS", DEPT_NO AS "NUMERO DEPARTAMENTO"
FROM EMPLE
GROUP BY DEPT_NO
HAVING COUNT(EMP_NO) > 4
ORDER BY COUNT(*) DESC;

--EJERCICIO 2
SELECT SUM(SALARIO) AS "SUMA DE LOS SALARIOS", MIN(SALARIO) "SALARIO MINIMO", MAX(SALARIO) AS "SALARIO MAXIMO"
FROM EMPLE
GROUP BY DEPT_NO;

--EJERCICIO 3
SELECT DEPT_NO, OFICIO, COUNT(EMP_NO) AS "NUM EMPLEADOS"
FROM EMPLE
GROUP BY OFICIO, DEPT_NO;

--EJERCICIO 4
SELECT COUNT(EMP_NO), DEPT_NO
FROM EMPLE
GROUP BY DEPT_NO;

SELECT MAX(COUNT(EMP_NO)) AS "NUM EMPLEADOS"
FROM EMPLE
GROUP BY DEPT_NO;
--EXTRA --> CODIGO Y NOMBRE DEL DEPARTAMENTO Y EL NUMERO MAXIMO DE EMPLEADOS (NO SACAR EL NUMERO)
--EJERCICIO 5
SELECT DEPT_NO AS "NUMERO DE DEPARTAMENTO", ROUND(AVG(SALARIO*12)) AS "SALARIO MEDIO ANUAL"
FROM EMPLE
GROUP BY DEPT_NO
HAVING MAX(SALARIO*12)>25000
ORDER BY DEPT_NO;

--EJERCICIO 6
SELECT ROUND(MAX(AVG(SALARIO))) AS "SALARIO MEDIO MAXIMO"
FROM EMPLE
GROUP BY DEPT_NO;

--EJERCICIO 7
SELECT COUNT(EMP_NO) AS "NUMERO EMPLEADOS", OFICIO
FROM EMPLE
GROUP BY OFICIO
ORDER BY OFICIO;

--EJERCICIO 8
SELECT ID_JEFE, MIN(SALARIO*12) AS "SALARIO MINIMO"
FROM EMPLE
WHERE ID_JEFE IS NOT NULL
GROUP BY ID_JEFE
HAVING MIN(SALARIO*12) <= 20000
ORDER BY MIN(SALARIO*12) DESC;