--EJERCICIO 1
SELECT * 
FROM EMPLE
WHERE SALARIO >(SELECT AVG(SALARIO) FROM EMPLE);

--EJERCICIO 2

SELECT APELLIDO, SALARIO, DEPT_NO
FROM EMPLE E
WHERE SALARIO > (SELECT AVG(SALARIO) 
                    FROM EMPLE
                    WHERE EMPLE.DEPT_NO= E.DEPT_NO);                
                    
--EJERCICIO 3

SELECT LOC
FROM DEPART
WHERE DEPT_NO IN (SELECT DEPT_NO
                    FROM EMPLE
                    WHERE COMISION_PCT>SALARIO*0.10);
                    
SELECT LOC
FROM DEPART
WHERE EXISTS (SELECT 'F'
                FROM EMPLE
                WHERE COMISION_PCT>SALARIO*0.10);


--EJERCICIO 4

SELECT APELLIDO
FROM EMPLE E
WHERE EXISTS (SELECT 'F'
                FROM EMPLE EE
                WHERE EE.DEPT_NO= E.DEPT_NO AND EE.FECHA_ALTA>E.FECHA_ALTA AND EE.SALARIO>E.SALARIO);
                

SELECT APELLIDO
FROM EMPLE E
WHERE 1 <=(SELECT COUNT(*)
                FROM EMPLE EE
                WHERE EE.DEPT_NO= E.DEPT_NO AND EE.FECHA_ALTA>E.FECHA_ALTA AND EE.SALARIO>E.SALARIO);
--EJERCICIO 5

SELECT DEPT_NO "NUMERO DEPARTAMENTO", DNOMBRE "NOMBRE DEPARTAMENTO"
FROM DEPART D
WHERE(SELECT COUNT (EMP_NO) FROM EMPLE WHERE DEPT_NO=D.DEPT_NO)=0;

SELECT DEPT_NO "NUMERO DEPARTAMENTO", DNOMBRE "NOMBRE DEPARTAMENTO"
FROM DEPART D
WHERE NOT EXISTS(SELECT 'F' FROM EMPLE WHERE DEPT_NO=D.DEPT_NO);