
CONSTRAINT_NAME                                                                                                                  TABLE_NAME                                                                                                                       C
-------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- -
ALU_FECHA_CK                                                                                                                     ALUMNOS                                                                                                                          C
BIN$Iw9OOECaTUWqPDMDYSVdLg==$0                                                                                                   BIN$yhzWEZ0DSRSy7Nbk5f3Qdg==$0                                                                                                   P
PROV_COD_PK                                                                                                                      PROVINCIAS                                                                                                                       P
BIN$JDy80QTyTOeZheCpmpORSA==$0                                                                                                   BIN$ZiJx34FNQQSXHyzvLsz0tQ==$0                                                                                                   P
BIN$zJO0qnUcR0eg3ZPwACUlJw==$0                                                                                                   BIN$IpA2hPeHSku9FjhR9bsb/A==$0                                                                                                   P
BIN$Fzu6Hy1DRZWDHR8MIIOePg==$0                                                                                                   BIN$uV3pCBxyT++PVbHf7b2PiQ==$0                                                                                                   P
BIN$Qz5zweyRSXuHfLr61DU4Vg==$0                                                                                                   BIN$rcqucDb4TJmOCtltz7NUPQ==$0                                                                                                   P
BIN$OpdMVZtFQS+fOuv8ENmJqg==$0                                                                                                   BIN$jMmwqBZfTTCJhe76tjeVog==$0                                                                                                   P
ALU_SEX_CK                                                                                                                       ALUMNOS                                                                                                                          C
SYS_C00119590                                                                                                                    ALUMNOS                                                                                                                          C
BIN$6QM+ohrfQcGDQktRu55f3g==$0                                                                                                   BIN$PQiC0fj5TFaRWBOg/5r3JQ==$0                                                                                                   P

CONSTRAINT_NAME                                                                                                                  TABLE_NAME                                                                                                                       C
-------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- -
BIN$+LZhxswwSgatufWT+kNVvw==$0                                                                                                   BIN$PQiC0fj5TFaRWBOg/5r3JQ==$0                                                                                                   C
BIN$5hb65e8DSFen3SZHujvEUQ==$0                                                                                                   BIN$PQiC0fj5TFaRWBOg/5r3JQ==$0                                                                                                   C
BIN$vcL1aISBQrOtKkc9AM+rJw==$0                                                                                                   BIN$PQiC0fj5TFaRWBOg/5r3JQ==$0                                                                                                   C
SYS_C00119595                                                                                                                    ALUMNOS                                                                                                                          C
BIN$CnLiCnzKSPO1duMzfoKzRQ==$0                                                                                                   BIN$FcTbh1nzQbabR7F8+ShvQw==$0                                                                                                   P
BIN$NJrU2sPwT4COFfhEbFZp/Q==$0                                                                                                   BIN$FcTbh1nzQbabR7F8+ShvQw==$0                                                                                                   C
BIN$2SDqq7zNQoqd4IvN0wuIvQ==$0                                                                                                   BIN$FcTbh1nzQbabR7F8+ShvQw==$0                                                                                                   C
BIN$aNqvQdErT92SNnF2zUcKOA==$0                                                                                                   BIN$FcTbh1nzQbabR7F8+ShvQw==$0                                                                                                   C
BIN$Ffctv0W+SNmIHMr7njk2RQ==$0                                                                                                   BIN$FcTbh1nzQbabR7F8+ShvQw==$0                                                                                                   C
BIN$gRdcryojRQKQb7xovwijcQ==$0                                                                                                   BIN$PQiC0fj5TFaRWBOg/5r3JQ==$0                                                                                                   C
DNI_PK                                                                                                                           ALUMNOS                                                                                                                          P

CONSTRAINT_NAME                                                                                                                  TABLE_NAME                                                                                                                       C
-------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- -
CURSO_CK                                                                                                                         ALUMNOS                                                                                                                          C
NOMBRE_CK                                                                                                                        ALUMNOS                                                                                                                          C
BIN$I7OYaivPS6KDTpoNJvzcJQ==$0                                                                                                   BIN$m52Na952R9aUQw19aS5JJQ==$0                                                                                                   C
BIN$vSV12i3gSoifioP7G4PnJg==$0                                                                                                   BIN$m52Na952R9aUQw19aS5JJQ==$0                                                                                                   P
BIN$qSHAsCdZTlSE1V+ziWlkdQ==$0                                                                                                   BIN$m52Na952R9aUQw19aS5JJQ==$0                                                                                                   C
BIN$O5f3PShtSzCIFtUqIPAsYg==$0                                                                                                   BIN$m52Na952R9aUQw19aS5JJQ==$0                                                                                                   C
BIN$/NEFL05JSs2dyuYmIB30zQ==$0                                                                                                   BIN$m52Na952R9aUQw19aS5JJQ==$0                                                                                                   C
BIN$ZLcz8h8URqOUYnIwDHIkJw==$0                                                                                                   BIN$m52Na952R9aUQw19aS5JJQ==$0                                                                                                   C

30 filas seleccionadas. 

